import discord
from discord import app_commands
from discord.ext import commands
from io import BytesIO
from ..services.image_service import ImageService
from ..config import config

class ImageCommands(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.image_service = ImageService(
            default_model=config.IMAGE_MODEL,
            auth_token=config.POLLINATIONS_TOKEN
        )
    
    @app_commands.command(name="imagine", description="Generate an image from text")
    @app_commands.describe(
        prompt="Describe the image you want to generate",
        model="AI model to use (flux, turbo, stable-diffusion)",
        width="Image width (default 1024)",
        height="Image height (default 1024)",
        enhance="Auto-enhance your prompt"
    )
    @app_commands.choices(model=[
        app_commands.Choice(name="Flux (High Quality)", value="flux"),
        app_commands.Choice(name="Turbo (Fast)", value="turbo"),
        app_commands.Choice(name="Stable Diffusion (Balanced)", value="stable-diffusion")
    ])
    async def imagine(
        self, 
        interaction: discord.Interaction, 
        prompt: str,
        model: str = None,
        width: int = 1024,
        height: int = 1024,
        enhance: bool = False
    ):
        """Generate an image using AI"""
        await interaction.response.defer()
        
        try:
            # Validate dimensions
            if width < 256 or width > 2048:
                await interaction.followup.send("Width must be between 256 and 2048 pixels!")
                return
            if height < 256 or height > 2048:
                await interaction.followup.send("Height must be between 256 and 2048 pixels!")
                return
            
            # Generate image
            image_url = await self.image_service.generate_image(
                prompt=prompt,
                model=model,
                width=width,
                height=height,
                enhance=enhance
            )
            
            # Get the model name
            used_model = model if model else self.image_service.get_current_model()
            
            # Create embed
            embed = discord.Embed(
                title="🎨 Image Generated!",
                description=f"**Prompt:** {prompt}",
                color=discord.Color.purple()
            )
            embed.add_field(name="Model", value=used_model.title(), inline=True)
            embed.add_field(name="Size", value=f"{width}x{height}", inline=True)
            embed.add_field(name="Enhanced", value="Yes" if enhance else "No", inline=True)
            embed.set_image(url=image_url)
            embed.set_footer(text=f"Generated by {interaction.user.name}")
            
            await interaction.followup.send(embed=embed)
            
        except Exception as e:
            await interaction.followup.send(f"❌ Error generating image: {str(e)}")
    
    @app_commands.command(name="imagemodel", description="Set the default image generation model")
    @app_commands.describe(model="Choose the default AI model")
    @app_commands.choices(model=[
        app_commands.Choice(name="Flux (High Quality)", value="flux"),
        app_commands.Choice(name="Turbo (Fast)", value="turbo"),
        app_commands.Choice(name="Stable Diffusion (Balanced)", value="stable-diffusion")
    ])
    async def set_image_model(self, interaction: discord.Interaction, model: str):
        """Set the default image generation model"""
        if self.image_service.set_model(model):
            await interaction.response.send_message(
                f"✅ Default image model set to: **{model.title()}**",
                ephemeral=True
            )
        else:
            await interaction.response.send_message(
                f"❌ Invalid model! Choose from: {', '.join(self.image_service.AVAILABLE_MODELS)}",
                ephemeral=True
            )
    
    @app_commands.command(name="imageinfo", description="Show current image generation settings")
    async def image_info(self, interaction: discord.Interaction):
        """Show current image generation settings"""
        current_model = self.image_service.get_current_model()
        
        embed = discord.Embed(
            title="🎨 Image Generation Settings",
            color=discord.Color.blue()
        )
        embed.add_field(name="Current Model", value=current_model.title(), inline=False)
        embed.add_field(
            name="Available Models", 
            value="\n".join(f"• {model}" for model in self.image_service.AVAILABLE_MODELS),
            inline=False
        )
        embed.add_field(name="Max Resolution", value="2048x2048", inline=True)
        embed.add_field(name="Min Resolution", value="256x256", inline=True)
        
        await interaction.response.send_message(embed=embed, ephemeral=True)

async def setup(bot):
    await bot.add_cog(ImageCommands(bot))
